import { DatabaseSync } from "node:sqlite";
import { readFileSync, readdirSync } from "node:fs";
import { createHash } from "node:crypto";
import { afterEach, describe, expect, it, vi } from "vitest";
import { createAgentImageGenerationServices, loadAgentGeneratedImageAction } from "./agent-image-generation";
import { syncManagedAiUsage } from "./managed-ai-billing";
import type { Env } from "./types";

const databases: DatabaseSync[] = [];
afterEach(() => { databases.splice(0).forEach(db => db.close()); vi.unstubAllGlobals(); });
const png = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/lZkAAAAASUVORK5CYII=";
const usage = { input_tokens: 10, output_tokens: 1800, total_tokens: 1810, input_tokens_details: { text_tokens: 10, image_tokens: 0 } };
const scope = { threadId: "thread", turnId: "turn", requestId: "request", idempotencyKey: "image-key", signal: new AbortController().signal };
function fixture(model = "openai/gpt-image-2", response: unknown = { data: [{ b64_json: png }], usage }) {
  const raw = new DatabaseSync(":memory:"); databases.push(raw); raw.exec("PRAGMA foreign_keys=ON");
  const directory = new URL("../migrations/", import.meta.url);
  for (const file of readdirSync(directory).filter(name => name.endsWith(".sql")).sort()) raw.exec(readFileSync(new URL(file, directory), "utf8"));
  raw.exec(`INSERT INTO owner_profile(id,username) VALUES('owner','synthetic'),('other','other-synthetic');
    INSERT INTO assistant_threads(id,owner_id,title) VALUES('thread','owner','Synthetic'),('foreign','other','Foreign');
    INSERT INTO me3_agent_turns(turn_id,owner_id,thread_id,request_id) VALUES('turn','owner','thread','request');
    INSERT INTO me3_agent_tool_receipts(owner_id,idempotency_key,turn_id,tool_name,arguments_json,status)
      VALUES('owner','image-key','turn','core_images_generate','{"prompt":"Synthetic flower"}','running');`);
  const db = { prepare(sql: string) { const query=raw.prepare(sql); let values:unknown[]=[];
    const statement={ bind(...args:unknown[]){values=args;return statement;},async first(){return query.get(...values as never[])??null;},async all(){return {results:query.all(...values as never[])};},async run(){return {meta:{changes:Number(query.run(...values as never[]).changes)}};} };return statement;
  },async batch(statements:Array<{run:()=>Promise<unknown>}>){raw.exec("BEGIN");try{const results=[];for(const statement of statements)results.push(await statement.run());raw.exec("COMMIT");return results;}catch(error){raw.exec("ROLLBACK");throw error;}} };
  const objects=new Map<string,Uint8Array>();
  const put=vi.fn(async(key:string,bytes:ArrayBuffer|Uint8Array)=>{objects.set(key,new Uint8Array(bytes));return {};});
  const get=vi.fn(async(key:string)=>{const bytes=objects.get(key);return bytes?{size:bytes.length,arrayBuffer:async()=>bytes.buffer}:null;});
  const remove=vi.fn(async(key:string)=>objects.delete(key));
  const run=vi.fn(async(_model:string,_input:unknown,_options:unknown)=>response);
  const env={DB:db,AI:{run},SITE_ASSETS:{put,get,delete:remove},ME3_DEPLOYMENT_MODE:"self_hosted",ME3_AI_IMAGE_GENERATION_MODEL:model,CLOUDFLARE_AI_GATEWAY_ID:"fixture"} as unknown as Env;
  return {raw,env,run,put,get,remove,objects,service:createAgentImageGenerationServices(env,"owner")!};
}
function managed(f:ReturnType<typeof fixture>, override:Record<string,unknown>={}) {
  f.env.ME3_DEPLOYMENT_MODE="managed";f.env.ME3_COMMERCE_BRIDGE_ORIGIN="https://billing.example.invalid";f.env.ME3_COMMERCE_BRIDGE_TOKEN="synthetic";
  const policy={available:true,managed:true,currency:"usd",eligible:true,ineligibleReason:null,billingSource:"internal",defaultModel:"openai/gpt-5.4-mini",models:[],overagesEnabled:false,includedMonthlyCents:500,monthlyMaximumCents:500,minimumMonthlyMaximumCents:600,maximumMonthlyMaximumCents:50000,currentMonth:new Date().toISOString().slice(0,7),currentMonthUsageMicrousd:0,currentMonthBillableMicrousd:0,effectiveMaximumCents:500,fallbackActive:false,...override};
  const events:unknown[]=[];const bridge=vi.fn(async(url:string,init?:RequestInit)=>{if(url.endsWith("/usage")){const batch=JSON.parse(String(init?.body)).events;events.push(...batch);return Response.json({acceptedEventIds:batch.map((e:{id:string})=>e.id),settings:policy});}return Response.json(policy);});vi.stubGlobal("fetch",bridge);return {policy,events,bridge};
}
describe("native private image generation operation",()=>{
  it("reserves before provider, saves a private authoritative asset and atomically finishes the generic receipt",async()=>{
    const f=fixture();f.run.mockImplementation(async()=>{expect(f.raw.prepare("SELECT status FROM me3_agent_image_operations").get()).toMatchObject({status:"admitted"});expect(JSON.parse(String(f.raw.prepare("SELECT metadata_json FROM ai_usage_events").get()!.metadata_json))).toMatchObject({costKnown:false,billingManaged:false});return {data:[{b64_json:png}],usage};});
    const result=await f.service.generate("Synthetic flower",scope);expect(result).toMatchObject({status:"complete",action:{kind:"generated",providerId:"workers-ai",model:"openai/gpt-image-2",assets:[{mimeType:"image/png",width:1,height:1,url:expect.stringMatching(/^\/api\/assistant\/attachments\//)}]}});
    expect(f.raw.prepare("SELECT status,result_json FROM me3_agent_tool_receipts").get()).toMatchObject({status:"finished",result_json:expect.stringContaining('"imageAction"')});
    expect(f.raw.prepare("SELECT estimated_cost_usd,tokens_in,tokens_out FROM ai_usage_events").get()).toMatchObject({estimated_cost_usd:0.05405,tokens_in:10,tokens_out:1800});
    expect(await createAgentImageGenerationServices(f.env,"owner")!.generate("Synthetic flower",scope)).toEqual(result);expect(f.run).toHaveBeenCalledTimes(1);expect(f.put).toHaveBeenCalledTimes(1);
    expect(await loadAgentGeneratedImageAction(f.env,{ownerId:"owner",threadId:"thread",turnId:"turn"})).toEqual(result.status==="complete"?result.action:null);
    expect(f.raw.prepare("SELECT COUNT(*) count FROM drive_files").get()).toMatchObject({count:0});
  });
  it.each([undefined,{}, {...usage,output_tokens:"1800"},{...usage,total_tokens:1},{...usage,input_tokens_details:undefined},{...usage,input_tokens:NaN},{...usage,output_tokens:0}])("delivers completed media but keeps incomplete accounting on hold: %j",async invalid=>{
    const f=fixture("openai/gpt-image-2",{data:[{b64_json:png}],usage:invalid});managed(f);expect(await f.service.generate("Synthetic flower",scope)).toMatchObject({status:"complete"});
    expect(JSON.parse(String(f.raw.prepare("SELECT metadata_json FROM ai_usage_events").get()!.metadata_json))).toMatchObject({costKnown:false,billingManaged:true});await syncManagedAiUsage(f.env);expect(f.raw.prepare("SELECT json_extract(metadata_json,'$.managedBillingReportedAt') reported FROM ai_usage_events").get()).toMatchObject({reported:null});
  });
  it("holds native fixed-unit accounting if the output dimensions do not match the requested 1024 square",async()=>{const f=fixture("@cf/black-forest-labs/flux-2-klein-4b",{image:png});expect(await f.service.generate("Synthetic flower",scope)).toMatchObject({status:"complete"});expect(JSON.parse(String(f.raw.prepare("SELECT metadata_json FROM ai_usage_events").get()!.metadata_json))).toMatchObject({costKnown:false});});
  it.each(["foreign-thread","wrong-prompt","missing-receipt","cancelled","aborted"])("rejects before storage/provider/reservation: %s",async bad=>{const f=fixture();const input={...scope};let prompt="Synthetic flower";if(bad==="foreign-thread")input.threadId="foreign";if(bad==="wrong-prompt")prompt="Other prompt";if(bad==="missing-receipt")f.raw.exec("DELETE FROM me3_agent_tool_receipts");if(bad==="cancelled")f.raw.exec("INSERT INTO me3_agent_cancellations(owner_id,request_id)VALUES('owner','request')");if(bad==="aborted"){const controller=new AbortController();controller.abort();input.signal=controller.signal;}expect(await f.service.generate(prompt,input)).toMatchObject({status:"failed"});expect(f.run).not.toHaveBeenCalled();expect(f.put).not.toHaveBeenCalled();expect(f.raw.prepare("SELECT COUNT(*) count FROM ai_usage_events").get()).toMatchObject({count:0});});
  it("never retries an uncertain provider outcome, including a reworded same-turn request",async()=>{const f=fixture();f.run.mockRejectedValue(new Error("Synthetic ambiguous transport"));const first=await f.service.generate("Synthetic flower",scope);expect(first).toMatchObject({status:"unknown"});expect(await f.service.generate("Synthetic flower",scope)).toMatchObject({status:"unknown"});f.raw.exec(`INSERT INTO me3_agent_tool_receipts(owner_id,idempotency_key,turn_id,tool_name,arguments_json,status)VALUES('owner','other-key','turn','core_images_generate','{"prompt":"Another flower"}','running')`);expect(await f.service.generate("Another flower",{...scope,idempotencyKey:"other-key"})).toMatchObject({status:"unknown"});expect(f.run).toHaveBeenCalledTimes(1);expect(f.put).not.toHaveBeenCalled();});
  it.each([{fallbackActive:true},{currentMonthUsageMicrousd:5_000_000},{eligible:false},{available:false}])("refuses image generation at an exhausted/unavailable hosted policy: %j",async policy=>{const f=fixture();managed(f,policy);expect(await f.service.generate("Synthetic flower",scope)).toMatchObject({status:"failed"});expect(f.run).not.toHaveBeenCalled();expect(f.raw.prepare("SELECT COUNT(*) count FROM ai_usage_events").get()).toMatchObject({count:0});});
  it("normalizes the actual new hosted receipt once through the Core outbox, preserving author locally",async()=>{const f=fixture();const {events}=managed(f);expect(await f.service.generate("Synthetic flower",scope)).toMatchObject({status:"complete"});await syncManagedAiUsage(f.env);await syncManagedAiUsage(f.env);expect(events).toEqual([expect.objectContaining({provider:"workers-ai",model:"gpt-image-2",kind:"image",costMicrousd:56753})]);expect(JSON.parse(String(f.raw.prepare("SELECT metadata_json FROM ai_usage_events").get()!.metadata_json))).toMatchObject({modelAuthor:"openai",baseCostUsd:0.05405,billingFeeRate:0.05,costKnown:true,billingManaged:true,managedBillingReportedAt:expect.any(String)});});
  it("does not bill a self-hosted image after transfer to managed",async()=>{const f=fixture();await f.service.generate("Synthetic flower",scope);const {events}=managed(f);await syncManagedAiUsage(f.env);expect(events).toEqual([]);});
  it.each(["deleted","wrong-owner","wrong-thread","wrong-key","wrong-mime","wrong-size"])("never reloads revoked or changed output: %s",async change=>{const f=fixture();await f.service.generate("Synthetic flower",scope);const sql:Record<string,string>={deleted:"status='deleted'","wrong-owner":"owner_id='other'","wrong-thread":"thread_id='foreign'","wrong-key":"storage_key='arbitrary'","wrong-mime":"mime_type='image/jpeg'","wrong-size":"size=size+1"};f.raw.exec(`UPDATE assistant_attachments SET ${sql[change]}`);expect(await loadAgentGeneratedImageAction(f.env,{ownerId:"owner",threadId:"thread",turnId:"turn"})).toBeNull();expect(await f.service.generate("Synthetic flower",scope)).toMatchObject({status:"failed"});expect(f.run).toHaveBeenCalledTimes(1);});
  it("holds invalid provider media without saving an arbitrary URL or MIME",async()=>{const f=fixture("openai/gpt-image-2",{data:[{b64_json:btoa("not an image")}],usage});expect(await f.service.generate("Synthetic flower",scope)).toMatchObject({status:"unknown"});expect(f.put).not.toHaveBeenCalled();});
  it.each(["mime","size"])("rejects a forged portable output contract even if asset and operation agree: %s",async change=>{const f=fixture();await f.service.generate("Synthetic flower",scope);f.raw.exec(change==="mime"?"UPDATE assistant_attachments SET mime_type='image/svg+xml';UPDATE me3_agent_image_operations SET mime_type='image/svg+xml'":"UPDATE assistant_attachments SET size=20000000;UPDATE me3_agent_image_operations SET size=20000000");expect(await loadAgentGeneratedImageAction(f.env,{ownerId:"owner",threadId:"thread",turnId:"turn"})).toBeNull();});
  it("caps streamed provider downloads without consuming the rest of an oversized response",async()=>{const f=fixture("openai/gpt-image-2",{image:"https://synthetic.r2.dev/result"});let reads=0;let cancelled=false;vi.stubGlobal("fetch",async()=>new Response(new ReadableStream({pull(controller){reads++;if(reads>4)controller.close();else controller.enqueue(new Uint8Array(6*1024*1024));},cancel(){cancelled=true;}})));expect(await f.service.generate("Synthetic flower",scope)).toMatchObject({status:"unknown"});expect(reads).toBeLessThan(5);expect(cancelled).toBe(true);expect(f.put).not.toHaveBeenCalled();});
  it("preserves committed private media when D1 loses the completion acknowledgement",async()=>{const f=fixture();const batch=f.env.DB.batch.bind(f.env.DB);let calls=0;f.env.DB.batch=vi.fn(async statements=>{const results=await batch(statements);if(++calls===2)throw new Error("Synthetic lost commit acknowledgement");return results;}) as typeof f.env.DB.batch;expect(await f.service.generate("Synthetic flower",scope)).toMatchObject({status:"complete"});expect(f.objects.size).toBe(1);expect(f.remove).not.toHaveBeenCalled();expect(await createAgentImageGenerationServices(f.env,"owner")!.generate("Synthetic flower",scope)).toMatchObject({status:"complete"});expect(f.run).toHaveBeenCalledTimes(1);});
  it("unwinds its provably unstarted reservation when Stop lands just after admission",async()=>{const f=fixture();const controller=new AbortController();const batch=f.env.DB.batch.bind(f.env.DB);let calls=0;f.env.DB.batch=vi.fn(async statements=>{const results=await batch(statements);if(++calls===1)controller.abort();return results;}) as typeof f.env.DB.batch;expect(await f.service.generate("Synthetic flower",{...scope,signal:controller.signal})).toMatchObject({status:"failed"});expect(f.run).not.toHaveBeenCalled();expect(f.raw.prepare("SELECT COUNT(*) count FROM ai_usage_events").get()).toMatchObject({count:0});expect(f.raw.prepare("SELECT COUNT(*) count FROM me3_agent_image_operations").get()).toMatchObject({count:0});});
  it("cannot delete a concurrent paid invocation's receipt by reusing its key with a mismatched prompt",async()=>{const f=fixture();let release!:()=>void;let entered!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});const started=new Promise<void>(resolve=>{entered=resolve;});f.run.mockImplementation(async()=>{entered();await gate;return {data:[{b64_json:png}],usage};});const first=f.service.generate("Synthetic flower",scope);await started;try{expect(await f.service.generate("Wrong prompt",scope)).toMatchObject({status:"failed"});expect(f.raw.prepare("SELECT status FROM me3_agent_image_operations").get()).toMatchObject({status:"admitted"});expect(f.raw.prepare("SELECT COUNT(*) count FROM ai_usage_events").get()).toMatchObject({count:1});}finally{release();await first;}expect(f.run).toHaveBeenCalledTimes(1);expect(await first).toMatchObject({status:"complete"});});
  it("does not admit a provider call against a preexisting orphan usage receipt",async()=>{const f=fixture();const id=`agent-image:${createHash("sha256").update(JSON.stringify(["owner",scope.idempotencyKey])).digest("hex")}:usage`;f.raw.prepare("INSERT INTO ai_usage_events(id,user_id,kind,provider,model,metadata_json)VALUES(?,'owner','image','workers-ai','openai/gpt-image-2','{\"costKnown\":false,\"original\":true}')").run(id);expect(await f.service.generate("Synthetic flower",scope)).toMatchObject({status:"failed"});expect(f.run).not.toHaveBeenCalled();expect(f.raw.prepare("SELECT metadata_json FROM ai_usage_events").get()).toMatchObject({metadata_json:'{"costKnown":false,"original":true}'});expect(f.raw.prepare("SELECT COUNT(*) count FROM me3_agent_image_operations").get()).toMatchObject({count:0});});
  it("preserves planned asset identity and verified hash before an uncertain R2 write",async()=>{const f=fixture();f.put.mockImplementation(async(key,bytes)=>{expect(f.raw.prepare("SELECT storage_key,sha256,mime_type,size FROM me3_agent_image_operations").get()).toMatchObject({storage_key:key,sha256:expect.stringMatching(/^[a-f0-9]{64}$/),mime_type:"image/png",size:new Uint8Array(bytes).length});throw new Error("Synthetic ambiguous R2 write");});expect(await f.service.generate("Synthetic flower",scope)).toMatchObject({status:"unknown"});expect(f.raw.prepare("SELECT status,storage_key,sha256 FROM me3_agent_image_operations").get()).toMatchObject({status:"unknown",storage_key:expect.any(String),sha256:expect.any(String)});expect(f.raw.prepare("SELECT COUNT(*) count FROM assistant_attachments").get()).toMatchObject({count:0});});
  it("disables Gateway retries/cache and correlates only opaque receipt IDs for authoritative reconciliation",async()=>{const f=fixture();const result=await f.service.generate("Synthetic flower",scope);expect(result.status).toBe("complete");expect(f.run.mock.calls[0][2]).toMatchObject({gateway:{id:"fixture",skipCache:true,retries:{maxAttempts:1},metadata:{me3_runtime:"agent",operationId:result.status==="complete"?result.operationId:"",me3_turn_id:scope.turnId,me3_request_id:scope.requestId,me3_thread_id:scope.threadId}}});expect(JSON.stringify((f.run.mock.calls[0][2] as {gateway:unknown}).gateway)).not.toContain("Synthetic flower");});
});
