import { test, expect } from "./fixtures/test";

// UI contract journey with synthetic API fixtures; no private account or live mail/calendar is used.
for (const mobile of [false, true]) for (const dark of [false, true]) {
  test(`Home and Chat parity on ${mobile ? 'phone' : 'desktop'} ${dark ? 'dark' : 'light'}`, async ({ page }, testInfo) => {
    await page.emulateMedia({ colorScheme: dark ? 'dark' : 'light' });
    await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1440, height: 1000 });
    const today = new Date().toLocaleDateString('en-CA');
    let completed = false;
    const thread = { id: 'main', title: 'Main conversation', status: 'active', isPrimary: true };
    await page.route('**/api/**', async route => {
      const url = new URL(route.request().url());
      const path = url.pathname.replace(/^\/api/, '');
      let data: unknown = {};
      if (path === '/auth/me') data = { ok: true, user: { id: 'home-ui-owner', username: 'owner', name: 'Demo Owner', email: 'demo@example.com' }, workspace: { hasProfileSite: true } };
      else if (path === '/sites') data = { sites: [] };
      else if (path === '/plugins') data = { plugins: [] };
      else if (path === '/navigation-features') data = { features: [] };
      else if (path === '/assistant/threads/primary') data = { thread };
      else if (path === '/assistant/threads') data = { threads: [thread] };
      else if (path.endsWith('/messages') && path.startsWith('/assistant')) data = { thread, messages: [{ id: 'message', role: 'assistant', text: '- First item with enough text to wrap across lines on a narrow screen.\n  continuation\n  - Nested item\n- Second item' }] };
      else if (path === '/assistant/jobs') data = { jobs: [] };
      else if (path === '/assistant/jobs/recipes') data = { recipes: [] };
      else if (path === '/assistant/settings') data = { settings: { name: 'ME3' } };
      else if (path === '/ai-settings') data = { deploymentMode: 'self_hosted', providers: [] };
      else if (path === '/mission-control/projects') data = { projects: [] };
      else if (path === '/calendar/feed') data = { events: [], bookings: [], reminders: [], tasks: [], sources: [] };
      else if (path === '/mission-control/approvals') data = { approvals: [] };
      else if (path === '/mailbox') data = { available: true, mailbox: { aliasAddress: 'me3@example.com' } };
      else if (path === '/mailbox/messages') data = { messages: [] };
      else if (path === '/soulink/status') data = { recentEvents: [] };
      else if (path === '/mission-control/tasks/due' && route.request().method() === 'PATCH') { completed = true; data = { task: { id: 'due', title: 'Send the proposal', status: 'done', updatedAt: new Date().toISOString() } }; }
      else if (path === '/mission-control/tasks') data = url.searchParams.has('cursor') ? { tasks: [{ id: 'due', title: 'Send the proposal', dueAt: today, status: completed ? 'done' : 'backlog', updatedAt: new Date().toISOString() }], nextCursor: null } : { tasks: [{ id: 'later', title: 'A later idea', dueAt: '2099-01-01', status: 'backlog' }, { id: 'done', title: 'Finished reel', status: 'done', updatedAt: new Date().toISOString() }], nextCursor: 'next' };
      else if (path === '/journal/archive') data = { entries: [{ id: 'journal-1', date: today, body: '- [ ] **A good day**. https://instagram.com/p/longurl More notes.' }] };
      else if (path === '/mission-control/dashboard') data = { settings: { goals: [] } };
      else if (path === '/mission-control/wheel') data = { snapshots: [], settings: { segments: [] } };
      await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(data) });
    });
    await page.goto('/assistant');
    const tasks = page.getByRole('article', { name: 'Tasks', exact: true });
    const journal = page.getByRole('article', { name: 'Journal', exact: true });
    await expect(tasks).toContainText('1 done today');
    await expect(tasks.locator('.home-line').first()).toContainText('Send the proposal');
    await expect(tasks).not.toContainText('Finished reel');
    await expect(journal).toContainText('Today');
    await expect(journal).toContainText('A good day.');
    await expect(journal).not.toContainText('https://');
    await expect(page.getByRole('button', { name: 'Start voice dictation', exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Send message', exact: true })).toHaveCount(0);
    const composer = page.getByLabel('Message composer');
    expect((await composer.boundingBox())!.height).toBeLessThan(80);
    await page.screenshot({ path: testInfo.outputPath('home.png'), fullPage: true });
    await page.getByRole('button', { name: 'Journal options' }).click();
    await page.getByRole('button', { name: 'Reorder cards', exact: true }).click();
    await page.getByRole('button', { name: 'Move Journal up' }).click();
    await page.getByRole('button', { name: 'Move Journal up' }).click();
    await page.getByRole('button', { name: 'Move Journal up' }).click();
    await page.getByRole('button', { name: 'Close Home editor' }).click();
    await page.reload();
    await expect(page.locator('.home-card').first()).toHaveAttribute('aria-label', 'Journal');
    await page.screenshot({ path: testInfo.outputPath('reloaded.png'), fullPage: true });
    await page.getByRole('button', { name: 'Journal options' }).click();
    await page.getByRole('button', { name: 'Remove from Home', exact: true }).click();
    await expect(journal).toHaveCount(0);
    await page.getByRole('button', { name: 'Add to Home', exact: true }).click();
    await page.getByRole('dialog').getByRole('button', { name: 'Journal', exact: true }).click();
    await expect(journal).toBeVisible();
    await page.getByRole('button', { name: 'Complete Send the proposal' }).click();
    await expect(tasks).toContainText('2 done today');
    await page.getByRole('button', { name: 'Chat', exact: true }).click();
    await expect(page.locator('.assistant-timeline ul ul')).toContainText('Nested item');
    await expect(page.locator('.assistant-timeline li').first()).toContainText('continuation');
    const draft = page.locator('#assistant-console-input');
    await draft.fill('First line\nSecond line\nThird line\nFourth line');
    await page.getByRole('button', { name: 'Chat', exact: true }).click();
    await expect.poll(async () => (await draft.boundingBox())!.height).toBeLessThanOrEqual(45);
    await draft.focus();
    await expect.poll(async () => (await draft.boundingBox())!.height).toBeGreaterThan(60);
    await draft.fill('Hello ME3');
    await expect(page.getByRole('button', { name: 'Send message', exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Start voice dictation', exact: true })).toHaveCount(0);
    await page.screenshot({ path: testInfo.outputPath('chat.png'), fullPage: true });
    await page.locator('#assistant-console-input').fill('');
    await page.getByLabel('Message options').click();
    await expect(page.getByLabel('Model', { exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Attach files', exact: true })).toBeVisible();
    await page.getByLabel('Message options').press('Escape');
    await expect(page.getByLabel('Model', { exact: true })).not.toBeVisible();
  });
}
