/** Only supported public media URLs can become background video sources. */
export function parseHeroVideo(value: unknown): { kind: "file" | "youtube"; url: string } | null {
  if (typeof value !== "string" || !value.trim()) return null;
  try {
    const url = new URL(value.trim());
    if (url.protocol !== "https:" || url.username || url.password) return null;
    const host = url.hostname.toLowerCase();
    if (["youtube.com", "www.youtube.com", "youtu.be", "www.youtube-nocookie.com"].includes(host)) {
      const id = host === "youtu.be" ? url.pathname.slice(1) : url.pathname.startsWith("/embed/") ? url.pathname.slice(7) : url.searchParams.get("v");
      if (!id || !/^[a-zA-Z0-9_-]{11}$/.test(id)) return null;
      return { kind: "youtube", url: `https://www.youtube-nocookie.com/embed/${id}?autoplay=1&mute=1&loop=1&playlist=${id}&controls=0&playsinline=1&rel=0` };
    }
    if (!/\.(mp4|webm)$/i.test(url.pathname)) return null;
    return { kind: "file", url: url.href };
  } catch { return null; }
}

const escape = (value: string) => value.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

export function renderHeroVideo(value: unknown): string {
  const video = parseHeroVideo(value);
  if (!video) return "";
  return video.kind === "youtube"
    ? `<iframe data-hero-video data-video-src="${escape(video.url)}" title="Background video" tabindex="-1" allow="autoplay; encrypted-media" referrerpolicy="strict-origin-when-cross-origin"></iframe>`
    : `<video data-hero-video data-video-src="${escape(video.url)}" muted loop playsinline preload="none" aria-hidden="true"></video>`;
}

export function heroVideoControls(value: unknown, links: Array<{ label: string; href: string }> = []): string {
  const video = parseHeroVideo(value);
  if (!video) return "";
  const policies = links.filter(link => /privacy|cookie|legal/i.test(link.label)).map(link => `<a href="${escape(link.href)}">${escape(link.label)}</a>`).join("");
  return `<div class="hero-video-controls"><button type="button" data-video-toggle hidden>Pause background video</button>${video.kind === "youtube" ? `<button type="button" data-cookie-settings>Cookie preferences</button>` : ""}</div>${video.kind === "youtube" ? `<dialog class="hero-consent" aria-labelledby="hero-consent-title"><button type="button" class="consent-close" data-consent-close aria-label="Close cookie preferences">×</button><h2 id="hero-consent-title">Cookie preferences</h2><p>We use cookies and similar technologies to ensure the proper functioning of this website and, with your consent, to display third-party content. You can accept, reject or manage your preferences.</p><div data-consent-details hidden><h3>Manage preferences</h3><label><input type="checkbox" checked disabled> Necessary</label><p>Required to remember your privacy choices and support essential site functions. Always active.</p><label><input type="checkbox" data-consent-media> Third-party content</label><p>Allows embedded YouTube videos. YouTube may use cookies and receive information about your visit.</p></div><form method="dialog"><button value="accept" class="consent-accept">Accept</button><button value="reject">Reject</button><button type="button" data-consent-preferences aria-expanded="false">Preferences</button><button value="save" data-consent-save hidden>Save preferences</button></form>${policies ? `<nav aria-label="Privacy information">${policies}</nav>` : ""}</dialog>` : ""}`;
}

export const heroVideoCss = `.pack-hero-background:has([data-hero-video]):after{background:rgba(244,241,234,.74)}.pack-hero-background:has([data-hero-video]) .button.primary{background:#18342f;color:#fff;border-color:#18342f}.pack-hero-media video{width:100%;height:100%;object-fit:cover}.pack-hero-media [data-hero-video]{position:absolute;inset:0;border:0;pointer-events:none}.pack-hero-media iframe{width:100%;height:100%;transform:scale(1.25)}.hero-video-controls{position:absolute;bottom:18px;right:24px;display:flex;flex-wrap:wrap;gap:8px;z-index:2}.hero-video-controls button,.hero-consent button{min-height:44px;padding:10px 16px;border:1px solid currentColor;border-radius:6px;background:#f4f1ea;color:#18342f;font:inherit;cursor:pointer}.hero-video-controls [hidden]{display:none}.hero-consent{position:fixed;inset:auto 16px 16px auto;width:min(480px,calc(100% - 32px));max-height:calc(100svh - 32px);overflow:auto;margin:0;padding:24px;border:1px solid #b5c3ba;border-radius:12px;background:#f4f1ea;color:#18342f;font:16px/1.5 system-ui;z-index:100}.hero-consent::backdrop{background:rgba(0,0,0,.35)}.hero-consent.hero-consent h2{margin:0 0 12px;font-size:24px}.hero-consent form{display:grid;gap:10px}.hero-consent button{width:100%;border-color:var(--consent-accent,#672321);color:#242126;background:#f3efe8}.hero-consent .consent-accept{background:var(--consent-accent,#672321);color:#fff}.hero-consent .consent-close{position:absolute;right:14px;top:12px;width:32px;min-height:32px;padding:0;border:0;font-size:26px}.hero-consent.hero-consent h2{text-align:center;font:600 16px/1.5 system-ui;margin:0 26px 28px}.hero-consent{background:#f3efe8;color:#242126;border:0;font-size:13px;padding:24px;border-radius:12px}.hero-consent p{margin:16px 0 24px}.hero-consent nav{display:flex;flex-wrap:wrap;justify-content:center;gap:12px;margin-top:18px}.hero-consent nav a{color:var(--consent-accent,#672321);text-decoration:underline}.hero-consent [hidden]{display:none}.hero-consent label{display:flex;gap:8px;align-items:center}.hero-consent.hero-consent h3{font-size:16px}.hero-consent button:focus-visible,.hero-video-controls button:focus-visible{outline:3px solid #18342f;outline-offset:3px}@media(prefers-reduced-motion:reduce){.pack-hero-media [data-hero-video]{display:none}}`;

/** Optional embeds have no src until consent. Storage failure safely falls back to session-only choice. */
export function heroVideoScript(): string {
  return `(()=>{const video=document.querySelector('[data-hero-video]');if(!video)return;const toggle=document.querySelector('[data-video-toggle]');const settings=document.querySelector('[data-cookie-settings]');const dialog=document.querySelector('.hero-consent');const motion=matchMedia('(prefers-reduced-motion: reduce)');const key='me3.youtube-consent.v1';let allowed=!dialog;let playing=false;try{if(dialog)allowed=localStorage.getItem(key)==='accept'}catch{}function stop(){if(video.tagName==='VIDEO')video.pause();else video.removeAttribute('src');playing=false;toggle.textContent='Play background video'}function play(){if(!allowed||motion.matches)return;if(!video.getAttribute('src'))video.setAttribute('src',video.dataset.videoSrc);if(video.tagName==='VIDEO'){video.muted=true;video.play().then(()=>{playing=true;toggle.textContent='Pause background video'}).catch(()=>{playing=false;toggle.textContent='Play background video'})}else{playing=true;toggle.textContent='Pause background video'}}function update(){toggle.hidden=!allowed||motion.matches;if(allowed&&!motion.matches)play();else stop()}toggle.addEventListener('click',()=>playing?stop():play());motion.addEventListener('change',update);if(dialog){const details=dialog.querySelector('[data-consent-details]');const media=dialog.querySelector('[data-consent-media]');const preferences=dialog.querySelector('[data-consent-preferences]');const save=dialog.querySelector('[data-consent-save]');settings.addEventListener('click',()=>{dialog.returnValue='';media.checked=allowed;dialog.showModal()});dialog.querySelector('[data-consent-close]').addEventListener('click',()=>dialog.close(''));preferences.addEventListener('click',()=>{details.hidden=!details.hidden;save.hidden=details.hidden;media.checked=allowed;preferences.setAttribute('aria-expanded',String(!details.hidden))});dialog.addEventListener('close',()=>{if(!['accept','reject','save'].includes(dialog.returnValue))return;allowed=dialog.returnValue==='accept'||(dialog.returnValue==='save'&&media.checked);try{localStorage.setItem(key,allowed?'accept':'reject')}catch{}update()});let saved=null;try{saved=localStorage.getItem(key)}catch{}if(!['accept','reject'].includes(saved))dialog.showModal()}update()})();`;
}
